-----------------------------------------------------------
-- Import Lua modules
----------------------------------------------------------
require('tuxedo.options')
require('tuxedo.keymaps')
require('tuxedo.cmp')
require('tuxedo.lsp')
require('tuxedo.latex')
require('tuxedo.prose')
require('tuxedo.plugins')
require('tuxedo.terminal')
require('tuxedo.python')
require('tuxedo.lua')
require('tuxedo.luasnip-config')
require('tuxedo.rmarkdown')
-- require('tuxedo.alpha')
-- require('tuxedo.autocommands')
require('tuxedo.autopairs')
require('tuxedo.bufferline')
require('tuxedo.impatient')
require('tuxedo.indentline')
require('tuxedo.lualine')
require('tuxedo.telescope')
require('tuxedo.whichkey')
require('tuxedo.vimwiki')
require('tuxedo.nvim-tree')
